data_root: /home/halas/Spatial Project/Spatial-Project/dataset/img
mask_root: 
  global_mask: /home/halas/Spatial Project/Spatial-Project/dataset/mask/global_mask
  random_sqaure_mask: /home/halas/Spatial Project/Spatial-Project/dataset/mask/random_sqaure_mask
  random_walk_mask: /home/halas/Spatial Project/Spatial-Project/dataset/mask/random_walk_mask

device: "cuda"
batch_size: 4
num_workers: 1
epochs: 1
input_nc: 3
ndf: 64
ngf: 64
lr: 0.0002
gan_type: "lsgan"
gan_weight: 1.0
lambda_A: 10.0
style_weight: 10.0
content_weight: 1.0
LBP:
  ngf: 64
  use_spectral_norm: true
GEN:
  ngf: 64
  use_spectral_norm: true


discounting: 1

fineSize: 256
overlap: 10