data_root: /home/halas/Spatial Project/Spatial-Project/dataset/img
mask_root: 
  global_mask: /home/halas/Spatial Project/Spatial-Project/dataset/mask/global_mask
  random_sqaure_mask: /home/halas/Spatial Project/Spatial-Project/dataset/mask/random_sqaure_mask
  random_walk_mask: /home/halas/Spatial Project/Spatial-Project/dataset/mask/random_walk_mask

type: "train"
batch_size: 1
loadSize: 256
fineSize: 256
input_nc: 3
output_nc: 3
ngf: 64
ndf: 64
dataset_mode: "aligned"
num_workers: 8
checkpoints_dir: "./weights"
norm: "instance"
suffix: ""
max_dataset_size: infinity
resize_or_crop: "resize_and_crop"
no_flip: false
init_type: "normal"
mask_type: "center"
mask_sub_type: "rect"
lambda_A: 100
overlap: 4
init_gain: 0.02
skip: 0
fuse: 0
gan_type: "vanilla"
gan_weight: 0.2
style_weight: 10.0
content_weight: 1.0
discounting: 1
use_spectral_norm_D: 1
use_spectral_norm_G: 0

# input_nc
# ndf
# device

LBP:
  ngf: 64
  use_spectral_norm: False

muli_level_loss_paramter: a
reconstruction_loss_parameter: a
adversal_loss_paramter: a

gan_loss_type: hinge